@framestackAPI_HostAddress = http://localhost:5151

#GET {{framestackAPI_HostAddress}}/weatherforecast/
#Accept: application/json
####
GET {{framestackAPI_HostAddress}}/picturesfromaccount/{{accountId}}/{{page}}/{{size}}/
Accept: application/json
###
GET {{framestackAPI_HostAddress}}/users/
Accept: application/json
###
POST {{framestackAPI_HostAddress}}/checkpassword/
Accept: application/json
###
POST {{framestackAPI_HostAddress}}/createuser/
Accept: application/json
###
POST {{framestackAPI_HostAddress}}/addusertofamily/
Accept: application/json
###
POST {{framestackAPI_HostAddress}}/uploadpicture/
Accept: application/json
###
